CXX=g++
CXXFLAGS=-std=c++14 -Wall -O2

all: A B C D E F

A: A.cpp
	$(CXX) $< $(CXXFLAGS) -o $@

B: B.cpp
	$(CXX) $< $(CXXFLAGS) -o $@

C: C.cpp
	$(CXX) $< $(CXXFLAGS) -o $@

D: D.cpp
	$(CXX) $< $(CXXFLAGS) -o $@

E: E.cpp
	$(CXX) $< $(CXXFLAGS) -o $@

F: F.cpp
	$(CXX) $< $(CXXFLAGS) -o $@
